### PR TITLE
various code style fixes

### PR DESCRIPTION
**Pull request by Findus23**
a few things that don't warrant a PR each:
- comparisons with None should always be done with `is None` (https://www.python.org/dev/peps/pep-0008/#programming-recommendations)
- a few missing parameters in the docstrings
- removing some trailing semicolons from C muscle memory :)
- `super(Class, self)` is supposed to be used with the superclass inside the `super()` call.

### CODE REVIEW

**Comment by hannorein** [comment]
Thanks. Are you sure about the super() syntax. I think I understand the [documentation](https://docs.python.org/3/library/functions.html#super) differently thank you. The one example they list is this:
```
class C(B):
    def method(self, arg):
        super().method(arg)   
```
The comment says the last line is the same as calling  `super(C, self).method(arg)`. Isn't that exactly what was in REBOUND before?

**Comment by hannorein** [comment]
Looks like travis agrees with me 😉

**Comment by Findus23** [comment]
You are of course right. I got myself completely confused.

**Comment by hannorein** [comment]
You almost convinced me! 

Thanks for the other changes. They all look good (but I'll way for travis to be sure). When I find some time, I'll look into linting a bit more. There are quite a few other inconsistencies I'd like to clean up. And as always, your help is much appreciated!

**Pull request merged**
