### PR TITLE
Angmom

### PR DESCRIPTION
**Pull request by dtamayo**
Added function to calculate angular momentum.  3 in c for each component.  Python returns a list.  From https://github.com/hannorein/rebound/issues/160

### CODE REVIEW

**Comment by dtamayo** [comment]
I tested that all three components are conserved in an IAS15 integration (phew!) ;)

**Comment by hannorein** [comment]
I'm glad the angular momentum is conserved! ;-)

Super minor, but it looks a little repetitive. Would it make sense to have one function and a return value with type `res_vec3d` or one void function with arguments `struct res_simulation sim, double* Lxyz)`?

**Comment by hannorein** [comment]
Merging it for now, feel free to change it later, if you think something like `reb_vec3d` makes sense...

**Comment by hannorein** [comment]
Super-super minor comment: unit tests! ;-)

**Comment by dtamayo** [comment]
Sure, I'm happy to do that.  In the code it said that reb_vec3d was only for internal use, so I didn't know if that was something you wanted to avoid exposing to the user.

**Comment by hannorein** [comment]
I saw little use for it. Maybe this is one?

**Pull request merged**
