### PR TITLE
Reset BS/IAS15 in TRACE to reduce file size

### PR DESCRIPTION
**Pull request by hannorein**
It would be nice to reduce the file size in TRACE integration. 

@tigerchenlu98, I naively thought these changes should not have any effects on the actual integration. But the units tests are failing. Do you understand why?

### CODE REVIEW

**Comment by hannorein** [comment]
Sorry, my bad: the unit tests pass! Do you see any downside coming from these changes? There should only be a negligible overhead in terms of runtime because the reset functions were already called at the beginning and calling them twice doesn't take long. But you have all these timing tests set up, so maybe you can verify that this is indeed the case?

**Comment by tigerchenlu98** [comment]
Hey Hanno,

I see no reason the actual integration should change. 

In terms of overhead, the only thing I'm concerned about is reallocing the nbody ode every time we call reset. I'm not sure if this would actually be an issue, but it's easily tested -- I'll run them and get back to you.

**Comment by tigerchenlu98** [comment]
I ran the tests for all three pericenter modes -- integrations were all completely identical and runtimes were not meaningfully longer (less than 1 percent), so I think this is good to go!

**Comment by hannorein** [comment]
We already call reset at the beginning of the step, and then reallocating everything, so I don't think there's a significant overhead. And your tests seem to confirm that! Thanks! I'll merge it in...

**Comment by hannorein** [comment]
Fixes #794

**Pull request merged**
