### PR TITLE
Suggestion about hash usage from python

### PR DESCRIPTION
**Pull request by hannorein**

### CODE REVIEW

**Comment by dtamayo** [comment]
I agree that's a nicer syntax for get_particle

**Comment by dtamayo** [comment]
I'll update the examples to reflect the syntax.

**Comment by hannorein** [comment]
On thing to check is to make sure it works on both python 2 and 3.

**Comment by dtamayo** [comment]
Does travis do python 2?

**Comment by hannorein** [comment]
It checks both.

**Pull request merged**
