### PR TITLE
A bunch of C examples and minor changes in src/display.c code

### PR DESCRIPTION
**Pull request by meldonization**
Hi Hanno, 

Thank you for the gorgeous code. I found rebound is perfect for amateur/scientific demonstrating. 

I've created two C examples: Stark force and eccentricity tidal damping of the hot Jupiter Class created by high-e migration. 

Also, some minor changes in 'display.c' like adding displaying the current integration time and default pause simulation at start when assigning OPENGL=1 (That would give me time for preparing screenshot or choose between different keyboard input.)

Well, You definitely don't need to merge them to the master repo, cause my programming skill sucks... To me, It's just a way of reaching out to the rebound creator's group. So I was wondering if we could have a Slack team for code/astro_case discussion (like implementing how to continue integration after rebound accidental quit). 

^_^  - Meldonization (mengzy1989@gmail.com)

### CODE REVIEW

**Comment by hannorein** [comment]
Thanks a lot. I do like the on screen text for OpenGL. Do you know if that is platform independent? I.e. will it work on different max/unix platforms? (what are you using?)

**Comment by meldonization** [comment]
Mine is OSX 10.9. The basic idea is simple, by reset the coordinate to 2D, pull out the OPENGL function -- `glutBitmapCharacter()` and display string contains `r->time`. The text color somehow doesn't work, which might related to the pre-drawing of the orbit/particle. 

```
glMatrixMode(GL_PROJECTION);
glPushMatrix(); // save
glLoadIdentity();// and clear
glMatrixMode(GL_MODELVIEW);
glPushMatrix();
glLoadIdentity();
glRasterPos2f(0.25,0.75);
	
char buf[50];
sprintf(buf, "t = %.2lf yrs", tnow/2.0/M_PI);
const char* p = buf;
do glutBitmapCharacter(GLUT_BITMAP_9_BY_15, *p); while(*(++p));
	
glMatrixMode(GL_PROJECTION);
glPopMatrix(); // revert back to the matrix
glMatrixMode(GL_MODELVIEW );
glPopMatrix();
```

**Comment by hannorein** [comment]
Thanks. I'll certainly reuse some of your code. I just need a bit of time. For example, I want to make sure this works on linux, etc.

**Comment by hannorein** [comment]
I'll close this PR as I merged some of the display.c changes. Thanks a lot for those!

**Pull request closed without merging**
