### PR TITLE
Python Collision Resolve Example

### PR DESCRIPTION
**Pull request by Rmelikyan**
Hi Hanno,

I've seen a number of issues/questions come up regarding handling collisions and how to better define these interactions. This has been well documented for the C side of REBOUND, but for Python, a user defined collision resolve is just a small mention.

It took time for me to figure it out, but I eventually did implement my own function for my work and have prepared this example notebook that you might consider adding to the ipython examples for others to reference!

I tried to follow similar language and commentary as you provide in many of your examples, but of course will appreciate any edits or corrections you have for this.

I hope this can be a useful addition to this code base!

-Robert M.

### CODE REVIEW

**Comment by Findus23** [comment]
Many thanks for the example, it nicely demonstrates the topic of #475.

Just a bit of feedback:
I think the `ps[i].x` lines are a bit verbose and hard to read. Maybe it is easier if you would before set the two particles to variables (`cp1=ps[i]`).

Also you don't need to add the three axis separately, something like `merged_planet = (cp1 * cp1.m + cp2 * cp2.m) / total_mass` should work directly.

I'd use ** instead of pow() as this is more familiar to non-C-users.

I had to use a diff-tool to find the difference between the two `my_merge()` as they look too similar. Maybe there is a way to merge them.

I'd also expand on the explanation why you would want to keep the fist particle or the more massive particle and what the implications of both are for things like N_active (in my Simulations I want the merged object to be of the same type as the more massive one, so I keep the more massive one and drop the other one)

s/vecotrs/vectors/g, s/reitterate/reiterate/g, s/impliment/implement :) 

A sentence in the beginning why this method might be better would be nice.


But this example should help people trying to simulate collisions a lot.

**Comment by Rmelikyan** [comment]
Great comments! I'll apply much of your suggested simplifications for user clarity. I'll push that in soon.

**Comment by hannorein** [comment]
Thanks to both of you. This is great. 

Just a bit of a general comment. This example is on the long side. Maybe it can be shortened without missing out on too much. The plots, for example, could be a bit simpler. I wouldn't bother putting all the label on, changing the font size, etc. That just distracts from the main point (how to write the collision_resolve function). 

I also had a hard time spotting the difference between the merge functions. Maybe one is enough? I don't think the second one really illustrates a new concept.

It's great that you added the doc string to your functions. But given this is a jupyter notebook, you could simply describe the function in a comment cell and don't bother with the doc string. (Again, just trying to keep it as concise as possible).

**Comment by Rmelikyan** [comment]
Hi Hanno,

When you have a minute, check my most recent commit for an update to the example.

Let me know if there are other improvements to be made :)

-R

**Comment by hannorein** [comment]
Thanks a lot! I've just shortened it a little more and corrected a few typos (and probably added a few more).

**Pull request merged**
