### PR TITLE
modified Simulation.py for hermes so that mini.contents can be used.

### PR DESCRIPTION
**Pull request by silburt**

### CODE REVIEW

**Comment by hannorein** [comment]
Are we sure this is not creating some circular reference now? I.e. `simulation` needs to know `ri_hermes` and vice versa?

**Comment by hannorein** [comment]
Oh, I think it works. Because you put it before `simulation._fields_`...

**Comment by hannorein** [comment]
In that case, I guess we could also change the `global` pointer?

**Comment by silburt** [comment]
Yes, we had talked about making sure it was before simulation._fields_. We could also change global to a pointer.

**Pull request merged**
