### PR TITLE
use HTTP API to connect to horizon

### PR DESCRIPTION
**Pull request by Findus23**
fixes https://github.com/hannorein/rebound/issues/569

for now just a work-in-progress until I get to do more testing.
But in theory it should do the exact same thing, but just a bit faster.

>    Ideally, this should not break the user facing REBOUND syntax.

:heavy_check_mark: the `getParticle()` call stayed the same
 
>    Try to use as few external packages as possible.

:heavy_check_mark: no external packages are used (normally I use requests, but for this I looked into using urllib directly)
 >   If external packages are needed, use the "default" ones as much as possible.

:heavy_check_mark: urllib is a built-in python package
 >   Astropy is great, but it is huge. It can probably query Horizons but I would try to avoid it as a dependency.

:heavy_check_mark: I agree
 >   Getting this to work with python 2+3 might require some care.

semi-:heavy_check_mark: It should work with Python 3.6 (only tested it with 3.9), but not with Python 2 (the urllib imports are different). I could add a fix for python2 if you want to.

The way I created the parameter was by going through the telnet steps and looking for related parameters. So in theory the response from the server should be identical.

I changed the way the output is parsed a bit (as it is no longer sending data line-by-line), but again I think that the end result should be the same. (I'll test it)

The used URL is https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%273%27&MAKE_EPHEM=%27YES%27&EPHEM_TYPE=%27VECTORS%27&CENTER=%27%400%27&REF_PLANE=%27ecliptic%27&STEP_SIZE=%272%27&REF_SYSTEM=%27J2000%27&VEC_CORR=%27NONE%27&OUT_UNITS=%27KM-S%27&CSV_FORMAT=%27NO%27&VEC_DELTA_T=%27NO%27&VEC_TABLE=%273%27&VEC_LABELS=%27NO%27 (using the json format doesn't seem any more useful)

### CODE REVIEW

**Comment by hannorein** [comment]
Wow. That was fast! It would be great if python 2 keeps working for a while (obviously not in the long term). There's probably a workaround for urllib, but I vaguely remember it being a bit of a mess (and there is some issue with outdated certificates for https if I remember correctly). We could also just keep the telnet code for python 2. At least that would not break anything for people.

**Comment by Findus23** [comment]
Okay, with https://github.com/Findus23/rebound/commit/5d500396e36f7d3e0dd7b4a2c111640de72ff9c5 this should now also work with python2 (at least a `print(getParticle("Earth"))` works with 2.7.18)

Honestly, if people have an OS outdated enough that it can't connect to a TLS 1.2 server they have bigger (security) issues than not being able to fetch orbital data :)

**Comment by Findus23** [comment]
In a quick test it seems like the results are the same:
```python
import datetime
from typing import Tuple

from rebound.horizons import getParticle
from rebound.horizons_old import getParticle as getParticle_old


def body_to_tuple(b) -> Tuple:
    return b.x, b.y, b.z, b.vx, b.vy, b.vz


date = datetime.datetime.now()
for body in ["Earth", "Venus", "12345", "Ceres"]:
    print(body)
    new_body = getParticle(body, date=date)
    old_body = getParticle_old(body, date=date)
    print(new_body)
    print(old_body)
    assert body_to_tuple(new_body) == body_to_tuple(old_body)
```

```text
Earth
Searching NASA Horizons for 'Earth'... 
Found: Earth-Moon Barycenter (chosen from query 'Earth')
Searching NASA Horizons for 'Earth'... Found: Target body name: Earth-Moon Barycenter (3).
<rebound.particle.Particle object at 0x7fea6feffe40, m=6.045825576341311e+24 x=148456851.6501895 y=-13573826.32860492 z=23503.37968385499 vx=2.32217727150802 vy=29.53012563437215 vz=-0.001126655300364376>
<rebound.particle.Particle object at 0x7fea6ff62ac0, m=6.045825574495058e+24 x=148456851.6501895 y=-13573826.32860492 z=23503.37968385499 vx=2.32217727150802 vy=29.53012563437215 vz=-0.001126655300364376>
Venus
Searching NASA Horizons for 'Venus'... 
Found: Venus Barycenter (chosen from query 'Venus')
Searching NASA Horizons for 'Venus'... Found: Target body name: Venus Barycenter (299).
<rebound.particle.Particle object at 0x7fea6feb9140, m=4.867466257521635e+24 x=31051644.49845732 y=-103299483.9933061 z=-3265259.176751748 vx=33.20184895262005 vy=10.25178602647772 vz=-1.77519362145828>
<rebound.particle.Particle object at 0x7fea6feffe40, m=4.867466257521636e+24 x=31051644.49845732 y=-103299483.9933061 z=-3265259.176751748 vx=33.20184895262005 vy=10.25178602647772 vz=-1.77519362145828>
12345
Searching NASA Horizons for '12345'... 
Found: 12345 (1993 FT8) 
/home/lukas/git/rebound/rebound/horizons.py:146: RuntimeWarning: Warning: Mass cannot be retrieved from NASA HORIZONS. Set to 0.
  warnings.warn("Warning: Mass cannot be retrieved from NASA HORIZONS. Set to 0.", RuntimeWarning)
Searching NASA Horizons for '12345'... Found: Target body name: 12345 (1993 FT8).
/home/lukas/git/rebound/rebound/horizons_old.py:149: RuntimeWarning: Warning: Mass cannot be retrieved from NASA HORIZONS. Set to 0.
  warnings.warn("Warning: Mass cannot be retrieved from NASA HORIZONS. Set to 0.", RuntimeWarning)
<rebound.particle.Particle object at 0x7fea6feb9040, m=0.0 x=226314035.554691 y=-305492108.9203821 z=-7691655.743053362 vx=12.74017896088603 vy=13.03357528301918 vz=-0.9311244138528765>
<rebound.particle.Particle object at 0x7fea6ff62ac0, m=0.0 x=226314035.554691 y=-305492108.9203821 z=-7691655.743053362 vx=12.74017896088603 vy=13.03357528301918 vz=-0.9311244138528765>
Ceres
Searching NASA Horizons for 'Ceres'... 
Found: 1 Ceres (A801 AA) 
Searching NASA Horizons for 'Ceres'... Found: Target body name: 1 Ceres (A801 AA).
<rebound.particle.Particle object at 0x7fea6feb9140, m=0.0 x=267164761.544882 y=320485536.3404564 z=-39316908.01407705 vx=-14.03527144238983 vy=10.32517501615261 vz=2.911388535793837>
<rebound.particle.Particle object at 0x7fea6feffe40, m=0.0 x=267164761.544882 y=320485536.3404564 z=-39316908.01407705 vx=-14.03527144238983 vy=10.32517501615261 vz=2.911388535793837>
```

The time needed seems to be 2-3s vs 10-11s using telnet

**Comment by hannorein** [comment]
Cool! Glad to see a big speed improvement! Telnet was always terribly slow. 2-3s is great. 

It's more common to have outdated certificates than you think (raising my hand). If it's a compute node on a cluster behind a firewall, then security is really not an issue. If anything goes wrong during a major update, it takes a long time to fix it...

**Comment by hannorein** [comment]
I think this is ready to merge, right?

**Comment by Findus23** [comment]
I just changed one minor thing (https://github.com/hannorein/rebound/pull/570/commits/8c1c77d59eee5a2a2d39b7df310fdcafe65fb313) and re-ran the Horizons.ipynb.

If the output of Horizons.ipynb looks good to you and the code works fine on your end, I think you can merge it.

**Comment by hannorein** [comment]
Great speedup! 

Untitled

**Pull request merged**
