### PR TITLE
Alice2

### PR DESCRIPTION
**Pull request by dtamayo**
minor fixes

### CODE REVIEW

**Comment by hannorein** [comment]
PS: You forgot to change the variable name in the example which is why travis failed...

**Comment by dtamayo** [comment]
Yeah, sorry about that.

**Comment by hannorein** [comment]
No worries, glad it worked as intended. Thanks for the pull request!

**Comment by dtamayo** [comment]
Yeah, that’s really useful.

**Comment by dtamayo** [comment]
I’m trying to track down a weird error where TestParticles.ipynb fails with clang, but not with gcc, saying with clang that there are no positive values so log scale fails…when I run the notebook myself (and I’ve compiled everything with clang), everything looks normal.

Also, it seems you took the Twitter.ipynb out.  Can I take out the travis test for it then?

Dan

**Comment by dtamayo** [comment]
But now it seems like your build on the same branch succeeded?  Hrm…

**Comment by hannorein** [comment]
I noticed that too. The error appears only sometimes... Confusing.

And yes, I'll remove twitter. With the next syntax, I could't get it into 140 characters ;-)

**Comment by dtamayo** [comment]
I guess I’ll leave it for now unless it comes back up.  I don’t think anything I changed should have affected TestParticles.ipynb.

**Comment by dtamayo** [comment]
Hah

**Pull request merged**
